name = "LaTeXTabulars"
uuid = "266f59ce-6e72-579c-98bb-27b39b5c037e"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.1.3"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXEscapes = "cf6549fa-34fa-4b85-907d-0f184605242c"

[compat]
ArgCheck = "1, 2"
DocStringExtensions = "0.8, 0.9"
LaTeXEscapes = "0.2.0"
julia = "1.10"

[extras]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LaTeXStrings", "Test"]
