name = "LaTeXTabulars"
uuid = "266f59ce-6e72-579c-98bb-27b39b5c037e"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "1.0.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LaTeXEscapes = "cf6549fa-34fa-4b85-907d-0f184605242c"

[compat]
ArgCheck = "1, 2"
DocStringExtensions = "0.8, 0.9"
LaTeXEscapes = "0.2.0"
julia = "1.10"
